### ISSUE TITLE
Primary key from schema avro

### ISSUE THREAD

**Issue by giulio1979** [celonis/kafka-ems-connector#58]
Hi, I am planning to use the connector to ship tables into celonis. I am using schema registry, avro for both primary key and value. 

Question is, the connector is able to use the primary key from Kafka as primary key in EMS?

**Comment by kowallen** [comment]
Hello giulio.
It is possible. If key fields are not present in value the you need to use HeaderToField plugin: https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/HeaderToField.html - it will transform specified key fields into value, so the extended value and extended schema will be accessible to connector.
